# Meta Data for SEO

## Homepage
title: Req
titleSeparator: "-"
titleAddition: 'Simple Go HTTP client with Black Magic'
description: 'Req is a Simple Go HTTP client with Black Magic (Less code and More efficiency).'

## Documentation
# docsVersion: "0.3"

## Open Graph
images:
- doks.png
ogLocale: en_US
domainTLD: req.cool
titleHome: Req

## Twitter Cards
twitterSite: "@imrocchan"
twitterCreator: "@imrocchan"

## Sitelinks Search Box
siteLinksSearchBox: false

## Chrome Browser
themeColor: "#fff"

# Images
quality: 85
bgColor: "#fff"
landscapePhotoWidths:
- 900
- 800
- 700
- 600
- 500
portraitPhotoWidths:
- 800
- 700
- 600
- 500
lqipWidth: 20x
smallLimit: "300"

# Footer
footer: Powered by <a class="text-muted"
  href="https://www.cloudflare.com/">Cloudflare</a>, <a class="text-muted"
  href="https://gohugo.io/">Hugo</a>, and <a class="text-muted"
  href="https://getdoks.org/">Doks</a>

# Feed
copyRight: Copyright (c) 2020-2022 roc
alert: true
alertDismissable: true
# alertText: "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText: HTTP3 support is incoming!
  <a class="alert-link stretched-link"
  href="https://getdoks.org/blog/doks-v0.2/">Check out Doks v0.2</a>

repoHost: GitHub
docsRepo: https://github.com/imroc/req
docsRepoBranch: master
docsRepoSubPath: ""
editPage: false
lastMod: false

options:
  lazySizes: true
  clipBoard: true
  instantPage: true
  flexSearch: true
  darkMode: false
  bootStrapJs: true
  breadCrumb: false
  highLight: true
  kaTex: false
  multilingualMode: true
  docsVersioning: false
  fullWidth: false

menu:
  section:
    auto: true
    collapsibleSidebar: false
